In [22]:

from sentence_transformers import SentenceTransformer

# model = SentenceTransformer('bert-base-nli-mean-tokens')

# model = SentenceTransformer('all-MiniLM-L6-v2')

model = SentenceTransformer('nli-distilroberta-base-v2')

In [23]:
sentences = [
    "Three years later, the coffin was still full of Jello.",
    "The fish dreamed of escaping the fishbowl and into the toilet where he saw his friend go.",
    "The person box was packed with jelly many dozens of months later.",
    "Standing on one's head at job interviews forms a lasting impression.",
    "It took him a month to finish the meal.",
    "He found a leprechaun in his walnut shell."
]

In [24]:
sentence_embeddings = model.encode(sentences)

In [25]:
sentence_embeddings.shape

(6, 768)

In [26]:
sentence_embeddings

array([[-1.25028208e-01,  1.15597703e-01, -4.77579832e-02, ...,
         2.05891468e-02, -4.50879961e-01,  2.20459223e-01],
       [ 5.87761402e-01, -6.87505722e-01, -2.19015002e-01, ...,
        -1.34770203e+00,  1.26304373e-03,  1.12379217e+00],
       [ 3.85604233e-01,  2.92195499e-01,  4.05890234e-02, ...,
        -8.30300272e-01, -6.34803116e-01,  7.23231077e-01],
       [ 5.04944742e-01,  4.27564293e-01,  3.34332526e-01, ...,
        -6.08245194e-01,  9.58820581e-02, -4.60678749e-02],
       [ 2.10133433e-01, -1.61997959e-01,  2.09570929e-01, ...,
        -8.38233888e-01,  7.10887849e-01,  5.72998464e-01],
       [-1.00651994e-01, -8.22317243e-01, -6.03609443e-01, ...,
         5.53670466e-01, -1.82688415e-01,  9.59426105e-01]], dtype=float32)

In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
cosine_similarity(
    [sentence_embeddings[0]],
    [sentence_embeddings[2]]
)

array([[0.5337436]], dtype=float32)

In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
# Load the original train.csv file
data = pd.read_csv('Precily_Text_Similarity.csv')

train_df = pd.read_csv('Precily_Text_Similarity.csv')[:2300]
valid_df = pd.read_csv('Precily_Text_Similarity.csv')[2300:2600]
test_df = pd.read_csv ('Precily_Text_Similarity.csv')[2600:3000]
print('Train: '+ str(len(train_df)))
print('Valid: '+ str(len(valid_df)))
print('Test: '+ str(len(test_df)))

print(train_df.size)
train_df.head(10)

Train: 2300
Valid: 300
Test: 400
4600


text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   
5  india to deport bollywood actress india has or...   
6  mutant book wins guardian prize a book about t...   
7  aids and climate top davos agenda climate chan...   
8  kennedy predicts bigger turnout voters   pent ...   
9  carry on star patsy rowlands dies actress pats...   

                                               text2  
0  gardener wins double in glasgow britain s jaso...  
1  amnesty chief laments war failure the lack of ...  
2  hanks greeted at wintry premiere hollywood sta...  
3  redford s vision of sundance despite sporting ...  
4  mauresmo opens with victory in la amelie maure...  
5  fosters buys stake in winemaker australian bre...  
6  jp morgan admits us slavery links thousands of...  
7  howl helps boost japan s cinemas japan s box o...  
8  ocean s twelve raids box office ocean s twelve...  
9  uk broadband gets speed injection broadband s ...

In [30]:
data.head()

text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  
0  gardener wins double in glasgow britain s jaso...  
1  amnesty chief laments war failure the lack of ...  
2  hanks greeted at wintry premiere hollywood sta...  
3  redford s vision of sundance despite sporting ...  
4  mauresmo opens with victory in la amelie maure...

In [31]:
# Turnig all text to lowercase
train_df['text1'] = train_df['text1'].str.lower()
valid_df['text1'] = valid_df['text1'].str.lower()
test_df['text1'] = test_df['text1'].str.lower()
print(train_df.size)
train_df.head()

4600


text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  
0  gardener wins double in glasgow britain s jaso...  
1  amnesty chief laments war failure the lack of ...  
2  hanks greeted at wintry premiere hollywood sta...  
3  redford s vision of sundance despite sporting ...  
4  mauresmo opens with victory in la amelie maure...

In [32]:
train_df['text2'] = train_df['text2'].str.lower()
valid_df['text2'] = valid_df['text2'].str.lower()
test_df['text2'] = test_df['text2'].str.lower()
print(train_df.size)

4600


In [33]:
# Removing stopwords

# import nltk
# stop=nltk.download('stopwords')
from nltk.corpus import stopwords

stop = stopwords.words('english')


train_df['text1'] = train_df['text1'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
valid_df['text1'] = valid_df['text1'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
test_df['text1'] = test_df['text1'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

train_df['text2'] = train_df['text2'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
valid_df['text2'] = valid_df['text2'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
test_df['text2'] = test_df['text2'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
print(train_df.size)
train_df.head()

4600


text1  \
0  broadband challenges tv viewing number europea...   
1  rap boss arrested drug find rap mogul marion s...   
2  player burn-out worries robinson england coach...   
3  hearts oak 3-2 cotonsport hearts oak set ghana...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  
0  gardener wins double glasgow britain jason gar...  
1  amnesty chief laments war failure lack public ...  
2  hanks greeted wintry premiere hollywood star t...  
3  redford vision sundance despite sporting cordu...  
4  mauresmo opens victory la amelie mauresmo mari...

In [34]:
# Save the train and test sets as separate CSV files
train_df.to_csv('train_split.csv', index=False)
test_df.to_csv('test_split.csv', index=False)
valid_df.to_csv('valid_split.csv', index=False)
print(train_df.size)

4600


In [35]:
from sentence_transformers import  util

In [36]:
import numpy as np

In [37]:
train_df['text1'][1]

'rap boss arrested drug find rap mogul marion suge knight arrested violating parole allegedly found marijuana. arrested barstow california saturday following alleged traffic offence. expected transferred state prison decision made whether released. mr knight founder death row records served 10-month jail term 2004 punching man parole assault conviction. police said mr knight stopped saturday performing illegal u-turn search car allegedly found marijuana. also accused insurance. 18-year-old woman car arrested providing false information fake id card. later released. second alleged violation previously served half nine-year sentence breaking terms parole. mr knight 39 jailed october 1996 following involvement fight rival gang hours rapper tupac shakur killed las vegas drive-by shooting. driving shakur car time shot head. time probation assaulting two musicians. mr knight former bodyguard set death row records early 1990s shakur dr dre among protegees. label always dogged allegations supp

In [38]:
our_sentence = train_df['text1'][0]
print(train_df['text1'][2])

sentences=train_df['text2'][0]
print(train_df['text2'][2])
# lets embed our sentence
my_embedding = model.encode(our_sentence)

# lets embed the corpus
embeddings = model.encode(sentences)
cos_sim = util.cos_sim(my_embedding, embeddings)
# arr=np.array(cos_sim[0][0])
cos_sim

player burn-out worries robinson england coach andy robinson says english rugby act prevent injury destroying players careers. without host big names six nations intensity professional rugby union hits players. injuries part sport look amount injuries occur english season robinson told bbc sport. think players probably going three four years taken careers. robinson missing entire midfield six nations likes jonny wilkinson mike tindall greenwood injured. rugby union become far physically demanding since game went professional nearly 10 years ago. result three major stakeholders english rugby launched injury audit find players coping. audit jointly funded professional rugby players association rugby football union premier rugby. far robinson concerned findings must ignored. think injury audit coming march got great information think everybody english game got look said. situation going get worse better think rugby whole got look this.
hanks greeted wintry premiere hollywood star tom hank

tensor([[0.0725]])

In [39]:
cos_sim[0][0]

tensor(0.0725)

In [40]:
arr=np.array([])

arr

array([], dtype=float64)

In [41]:

for i in range(0,len(train_df)):
    our_sentence = train_df['text1'][i]
    sentences=train_df['text2'][i]
    # lets embed our sentence
    my_embedding = model.encode(our_sentence)

    # lets embed the corpus
    embeddings = model.encode(sentences)
    cos_sim = util.cos_sim(my_embedding, embeddings)
    arr=np.append(arr,cos_sim[0][0])


In [42]:
arr[30:60]

array([0.19094315, 0.28409675, 0.32717323, 0.19726649, 0.13692302,
       0.16167167, 0.30179334, 0.47565043, 0.40586537, 0.21648917,
       0.25958186, 0.24843773, 0.37900972, 0.15826276, 0.18959713,
       0.08808461, 0.49945635, 0.19901776, 0.25543529, 0.15370959,
       0.40550828, 0.15531385, 0.36470219, 0.31945211, 0.08248959,
       0.46749586, 0.40114468, 0.20808339, 0.27681464, 0.17962904])

In [43]:
arr.size

2300

In [44]:
arr1=np.array([])

In [45]:

for i in range(2600,2600+len(test_df)):
    our_sentence = test_df['text1'][i]
    sentences=test_df['text2'][i]
    # lets embed our sentence
    my_embedding = model.encode(our_sentence)

    # lets embed the corpus
    embeddings = model.encode(sentences)
    cos_sim = util.cos_sim(my_embedding, embeddings)
    arr1=np.append(arr1,cos_sim[0][0])

In [46]:
arr1[:20]

array([0.20839438, 0.13068968, 0.10042529, 0.20087135, 0.22980574,
       0.26248324, 0.10625503, 0.23094285, 0.22616258, 0.56926095,
       0.3363871 , 0.04895781, 0.48697948, 0.3257432 , 0.22288868,
       0.26180732, 0.19719791, 0.449898  , 0.46299189, 0.05386141])

In [47]:
arr1.size


400

In [48]:
arr2=np.array([])

In [49]:
for i in range(2300,2300+len(valid_df)):
    our_sentence = valid_df['text1'][i]
    sentences=valid_df['text2'][i]
    # lets embed our sentence
    my_embedding = model.encode(our_sentence)

    # lets embed the corpus
    embeddings = model.encode(sentences)
    cos_sim = util.cos_sim(my_embedding, embeddings)
    arr2=np.append(arr2,cos_sim[0][0])

In [15]:
arr2.size

0

In [16]:
arr2[0:20]

array([], dtype=float64)

In [17]:
## SHuffle the train test split

In [18]:
train_df.shape

(2300, 2)

In [50]:
train_df['cosineSimilarity']=arr.tolist()

In [51]:
train_df

text1  \
0     broadband challenges tv viewing number europea...   
1     rap boss arrested drug find rap mogul marion s...   
2     player burn-out worries robinson england coach...   
3     hearts oak 3-2 cotonsport hearts oak set ghana...   
4     sir paul rocks super bowl crowds sir paul mcca...   
...                                                 ...   
2295  wolves appoint hoddle manager glenn hoddle unv...   
2296  stars pay tribute actor davis hollywood stars ...   
2297  slow start speedy net services faster broadban...   
2298  lacroix label bought us firm luxury goods grou...   
2299  michael film signals retirement singer george ...   

                                                  text2  cosineSimilarity  
0     gardener wins double glasgow britain jason gar...          0.072456  
1     amnesty chief laments war failure lack public ...          0.356662  
2     hanks greeted wintry premiere hollywood star t...          0.157503  
3     redford vision sundance despite sporting cordu...          0.236179  
4     mauresmo opens victory la amelie mauresmo mari...          0.287220  
...                                                 ...               ...  
2295  shares hit ms drug suspension shares elan biog...          0.288460  
2296  ethnic producers face barriers minority ethnic...          0.298304  
2297  uk helps raped rwandan women britain give £4m ...          0.124620  
2298  playstation 3 processor unveiled cell processo...          0.240449  
2299  plan give elderly care control elderly disable...          0.271216  

[2300 rows x 3 columns]

In [62]:
train_df['text1'][2297]

'slow start speedy net services faster broadband uk becoming reality internet providers offer super-fast services. lucky britons already take advantage uk online 8 megabits per second service launched november 2004. bt retail announced trial speed service national rollout year end. service providers expected follow suit glut new voice video services follow. bandwidth isps buy said jill finger research director analyst firm idc. others watching bt retail trials initially employees later summer customers interest. bt retail said super-fast service could way differentiating players. losing market share could one way gaining back said ms finger. wanadoo set trial 8mbps service summer also plans roll unbundled services - means takes network bt - provide speeds 15mbps. timetable moment. cable firms ntl telewest also bound increase bandwidth time future according ntl spokesman better position bt long term. bt network limited compared cable. services coming stream video demand question 8mbps e

In [63]:
train_df['text2'][2297]

'uk helps raped rwandan women britain give £4m grant help women survivors rwandan genocide raped often deliberately infected hiv/aids. estimated 25 000 girls women raped 1994 genocide. 800 000 tutsis moderate hutus killed hutu militias assassination ethnic hutu leader. five-year department international development funding enable survivors access anti-retroviral treatment. plight infected women overshadowed long time. overshadowed rwanda emergence 100 days slaughter time mass killings took place women fate largely taboo subject. many women widowed children care many cases orphans too. women die number rwanda orphans rises. recently women access anti-retroviral treatment. starting change. funding intended make anti-retrovirals care available 2 500 women. mary kayitesi blewitt founder survivors fund (surf) one organisations funds channelled said recognition late survivors priority help.'

In [52]:
train_df[train_df['cosineSimilarity']>0.6]

text1  \
83    kennedy looks election gains may know quite de...   
139   fit-again betsen france squad france brought f...   
152   moody joins england lewis moody flown dublin j...   
226   us adds jobs expected us economy added 337 000...   
251   economy strong election year uk businesses set...   
267   taylor poised scotland return simon taylor nam...   
365   lennon brands rangers favourites celtic neil l...   
601   day-lewis set berlin honour actor daniel day-l...   
625   aviator wins top globes accolades aviator name...   
690   virgin blue shares plummet 20% shares australi...   
760   us manufacturing expands us industrial product...   
830   beckham virus spotted net virus writers tradin...   
1023  egypt sell state-owned bank egyptian governmen...   
1431  pountney handed ban fine northampton coach bud...   
1484  u2 desire number one u2 three prestigious gram...   
1523  sluggish economy hits german jobs number peopl...   
1555  critics back aviator oscars martin scorsese av...   
1918  cudicini misses carling cup final chelsea goal...   
2092  fresh hope argentine crisis three years argent...   
2113  tsunami cost sri lanka $1.3bn sri lanka faces ...   

                                                  text2  cosineSimilarity  
83    howard rejects bnp claim tory leader michael h...          0.606928  
139   england 17-18 france england suffered eighth d...          0.610524  
152   harinordoquy suffers france axe number eight i...          0.687409  
226   consumer spending lifts us growth us economic ...          0.649653  
251   bank opts leave rates hold bank england left i...          0.667320  
267   irish finish home game republic ireland manage...          0.645870  
365   bortolami predicts dour contest italy skipper ...          0.653276  
601   tautou film tops cesar prize nods french film ...          0.731497  
625   berlin celebrates european cinema organisers s...          0.600842  
690   nortel $300m profit revision telecoms equipmen...          0.646561  
760   latin america sees strong growth latin america...          0.634359  
830   windows worm travels tetris users warned windo...          0.736045  
1023  ukraine revisits state sell-offs ukraine prepa...          0.652430  
1431  old firm pair handed suspensions celtic henri ...          0.766695  
1484  cult band kasabian surge forward indie dance b...          0.641524  
1523  ecb holds rates amid growth fears european cen...          0.702867  
1555  director nair vanity project indian film direc...          0.608748  
1918  moyes u-turn beattie dismissal everton manager...          0.671812  
2092  palestinian economy decline despite short-live...          0.718658  
2113  asia quake increases poverty risk nearly two m...          0.748747

In [53]:
train_df['text1'][2113]

'tsunami cost sri lanka $1.3bn sri lanka faces $1.3bn (£691m) bill 2005 reconstruction tsunami killed 30 000 people central bank says. estimate preliminary bank governor sunil mendis told reporters could rise 2006. island state asking $320m international monetary fund help pay relief said. bank 5bn rupees ($50m; £27m) set aside lend lower interest rate lost property. according mr mendis half imf support could come freeze debt repayments would free resources immediately. rest could come five-year emergency loan. sri lanka hoping wider freeze creditors. paris club 19 creditors meets 12 january discuss debt moratorium nations hit tsunami ravaged south east asia 26 december. 150 000 people across region feared dead millions left homeless destitute. full reckoning economic cost sri lanka tsunami clear time come. already looks likely growth first half 2005 slow mr mendis told reporters although would say much. one side-effect disaster value rupee risen foreign funds flooded country. currency

In [54]:
test_df['cosineSimilarity']=arr1.tolist()

In [55]:
valid_df['cosineSimilarity']=arr2.tolist()

In [56]:
valid_df[valid_df['cosineSimilarity']>0.6]

text1  \
2304  spurs sign iceland u21 star tottenham primed s...   

                                                  text2  cosineSimilarity  
2304  spurs sign iceland u21 star tottenham primed s...               1.0

In [57]:
test_df[test_df['cosineSimilarity']>0.6]

text1  \
2720  ferguson fears milan cutting edge manchester u...   
2751  parmalat boasts doubled profits parmalat itali...   
2820  banker loses sexism claim former executive lon...   
2946  uk economy ends year spurt uk economy grew est...   

                                                  text2  cosineSimilarity  
2720  iranian misses israel match iranian striker va...          0.619000  
2751  umbro profits lifted euro 2004 uk sportswear f...          0.618543  
2820  banker loses sexism claim former executive lon...          1.000000  
2946  consumers drive french economy france economic...          0.865136

In [58]:
test_df['text1'][2820]

'banker loses sexism claim former executive london offices merrill lynch lost £7.5m ($14.6m) sex discrimination case us investment bank. employment tribunal dismissed stephanie villalba allegations sexual discrimination unequal pay. 42-year-old claim unfair dismissal resulting sacking august 2003. partial victory likely cap compensation £55 000 tiny fraction asked for. extent damages assessed new year. action - biggest claim heard employment tribunal uk - viewed something test case. tribunal decided ms villalba unfairly dismissed removed senior post entitled wait see suitable alternative position could found organisation. ms villalba former head merrill private client business europe made decision whether appeal. spokesman lawyers described decision disappointing pointed criticism merrill procedures within lengthy judgement. tribunal upheld ms villalba claim victimisation certain specific issues including bullying e-mails connection contract said found evidence laddish culture bank. sa

In [ ]:
test_df['text1'][2720]

In [59]:
train_df.to_csv('train_split.csv', index=False)
test_df.to_csv('test_split.csv', index=False)
valid_df.to_csv('valid_split.csv', index=False)

In [227]:
import torch

In [228]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
model.to(device)

cuda


SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Normalize()
)

In [229]:
torch.cuda.empty_cache()